version: "3"
services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 546326
      MYSQL_USER: naru
      MYSQL_PASSWORD: 546326
      MYSQL_DATABASE: movies
    ports:
      - "3312:3306"
    volumes:
      - /init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge